name    'hardening/mysql_hardening'
version '0.1.0'
source 'https://github.com/TelekomLabs/puppet-mysql-hardening'
author 'Dominik Richter'
license 'Apache License, Version 2.0'
summary 'Configures MySQL for security hardening'
description 'Configures MySQL for security hardening'
project_page 'https://github.com/TelekomLabs/puppet-mysql-hardening'
